import type { Table, Relation } from "../types";

export function exportMySQLDDL(
  tables: Table[],
  relations: Relation[]
): string {
  const fkMap = new Map<string, Relation[]>();

  relations.forEach((r) => {
    if (!fkMap.has(r.sourceTableId)) {
      fkMap.set(r.sourceTableId, []);
    }
    fkMap.get(r.sourceTableId)!.push(r);
  });

  const ddl: string[] = [];
  ddl.push("-- Auto-generated MySQL DDL");
  ddl.push("-- Generated by ERD Builder");
  ddl.push("");

  for (const table of tables) {
    ddl.push(`CREATE TABLE \`${table.name}\` (`);

    const columnLines: string[] = [];

    table.columns.forEach((col) => {
      let line = `  \`${col.name}\` ${col.type}`;

      if (col.isPk) {
        line += " NOT NULL";
      }

      columnLines.push(line);
    });

    const pkCols = table.columns
      .filter((c) => c.isPk)
      .map((c) => `\`${c.name}\``);

    if (pkCols.length > 0) {
      columnLines.push(`  PRIMARY KEY (${pkCols.join(", ")})`);
    }

    ddl.push(columnLines.join(",\n"));
    ddl.push(");");
    ddl.push("");
  }

  ddl.push("-- Foreign Keys");
  ddl.push("");

  relations.forEach((r) => {
    const source = tables.find((t) => t.id === r.sourceTableId);
    const target = tables.find((t) => t.id === r.targetTableId);
    if (!source || !target) return;

    const fkCol = r.label || `${target.name}_id`;

    ddl.push(
      `ALTER TABLE \`${source.name}\`
ADD CONSTRAINT \`fk_${source.name}_${target.name}\`
FOREIGN KEY (\`${fkCol}\`)
REFERENCES \`${target.name}\`(\`id\`)
ON DELETE CASCADE;`
    );
    ddl.push("");
  });

  return ddl.join("\n");
}
